"""empty message

Revision ID: 0a43721eadb1
Revises: 361c02308a38
Create Date: 2020-02-05 17:16:58.242165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43721eadb1'
down_revision = '361c02308a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fota_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fota_session')
    # ### end Alembic commands ###
