"""empty message

Revision ID: 2e9bb3030d1b
Revises: 47e4d4f2e742
Create Date: 2020-04-16 15:50:30.212089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9bb3030d1b'
down_revision = '47e4d4f2e742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fota_session', sa.Column('client', sa.Integer(), nullable=True))
    op.add_column('fota_session', sa.Column('device', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fota_session', 'device', ['device'], ['id'])
    op.create_foreign_key(None, 'fota_session', 'client', ['client'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fota_session', type_='foreignkey')
    op.drop_constraint(None, 'fota_session', type_='foreignkey')
    op.drop_column('fota_session', 'device')
    op.drop_column('fota_session', 'client')
    # ### end Alembic commands ###
