"""empty message

Revision ID: a476ce4fa2b7
Revises: 0a43721eadb1
Create Date: 2020-02-17 21:49:36.305146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a476ce4fa2b7'
down_revision = '0a43721eadb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deviceMQTT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('device', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deviceMQTT')
    # ### end Alembic commands ###
