"""empty message

Revision ID: a4e892038aa1
Revises: 2e9bb3030d1b
Create Date: 2020-04-30 12:20:59.951887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e892038aa1'
down_revision = '2e9bb3030d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fota_session', sa.Column('used', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fota_session', 'used')
    # ### end Alembic commands ###
